// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protobuf-nio-sample/src/main/proto/HeartBeat.proto
// Protobuf Java Version: 4.29.2

package com.github.quantranuk.protobuf.nio.proto;

public final class TestHeartBeat {
  private TestHeartBeat() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      TestHeartBeat.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeartBeatRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.quantranuk.protobuf.nio.proto.HeartBeatRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 requestTimeMillis = 1;</code>
     * @return The requestTimeMillis.
     */
    long getRequestTimeMillis();

    /**
     * <code>string requestMessage = 2;</code>
     * @return The requestMessage.
     */
    java.lang.String getRequestMessage();
    /**
     * <code>string requestMessage = 2;</code>
     * @return The bytes for requestMessage.
     */
    com.google.protobuf.ByteString
        getRequestMessageBytes();
  }
  /**
   * Protobuf type {@code com.github.quantranuk.protobuf.nio.proto.HeartBeatRequest}
   */
  public static final class HeartBeatRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.github.quantranuk.protobuf.nio.proto.HeartBeatRequest)
      HeartBeatRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 2,
        /* suffix= */ "",
        HeartBeatRequest.class.getName());
    }
    // Use HeartBeatRequest.newBuilder() to construct.
    private HeartBeatRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private HeartBeatRequest() {
      requestMessage_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.internal_static_com_github_quantranuk_protonio_sample_HeartBeatRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.internal_static_com_github_quantranuk_protonio_sample_HeartBeatRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest.class, com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest.Builder.class);
    }

    public static final int REQUESTTIMEMILLIS_FIELD_NUMBER = 1;
    private long requestTimeMillis_ = 0L;
    /**
     * <code>int64 requestTimeMillis = 1;</code>
     * @return The requestTimeMillis.
     */
    @java.lang.Override
    public long getRequestTimeMillis() {
      return requestTimeMillis_;
    }

    public static final int REQUESTMESSAGE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object requestMessage_ = "";
    /**
     * <code>string requestMessage = 2;</code>
     * @return The requestMessage.
     */
    @java.lang.Override
    public java.lang.String getRequestMessage() {
      java.lang.Object ref = requestMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string requestMessage = 2;</code>
     * @return The bytes for requestMessage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestMessageBytes() {
      java.lang.Object ref = requestMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestTimeMillis_ != 0L) {
        output.writeInt64(1, requestTimeMillis_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requestMessage_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, requestMessage_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestTimeMillis_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, requestTimeMillis_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requestMessage_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, requestMessage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest)) {
        return super.equals(obj);
      }
      com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest other = (com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest) obj;

      if (getRequestTimeMillis()
          != other.getRequestTimeMillis()) return false;
      if (!getRequestMessage()
          .equals(other.getRequestMessage())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTTIMEMILLIS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestTimeMillis());
      hash = (37 * hash) + REQUESTMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getRequestMessage().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.quantranuk.protobuf.nio.proto.HeartBeatRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.quantranuk.protobuf.nio.proto.HeartBeatRequest)
        com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.internal_static_com_github_quantranuk_protonio_sample_HeartBeatRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.internal_static_com_github_quantranuk_protonio_sample_HeartBeatRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest.class, com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest.Builder.class);
      }

      // Construct using com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        requestTimeMillis_ = 0L;
        requestMessage_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.internal_static_com_github_quantranuk_protonio_sample_HeartBeatRequest_descriptor;
      }

      @java.lang.Override
      public com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest getDefaultInstanceForType() {
        return com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest build() {
        com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest buildPartial() {
        com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest result = new com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.requestTimeMillis_ = requestTimeMillis_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.requestMessage_ = requestMessage_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest) {
          return mergeFrom((com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest other) {
        if (other == com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest.getDefaultInstance()) return this;
        if (other.getRequestTimeMillis() != 0L) {
          setRequestTimeMillis(other.getRequestTimeMillis());
        }
        if (!other.getRequestMessage().isEmpty()) {
          requestMessage_ = other.requestMessage_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                requestTimeMillis_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                requestMessage_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long requestTimeMillis_ ;
      /**
       * <code>int64 requestTimeMillis = 1;</code>
       * @return The requestTimeMillis.
       */
      @java.lang.Override
      public long getRequestTimeMillis() {
        return requestTimeMillis_;
      }
      /**
       * <code>int64 requestTimeMillis = 1;</code>
       * @param value The requestTimeMillis to set.
       * @return This builder for chaining.
       */
      public Builder setRequestTimeMillis(long value) {

        requestTimeMillis_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 requestTimeMillis = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestTimeMillis() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestTimeMillis_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object requestMessage_ = "";
      /**
       * <code>string requestMessage = 2;</code>
       * @return The requestMessage.
       */
      public java.lang.String getRequestMessage() {
        java.lang.Object ref = requestMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string requestMessage = 2;</code>
       * @return The bytes for requestMessage.
       */
      public com.google.protobuf.ByteString
          getRequestMessageBytes() {
        java.lang.Object ref = requestMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestMessage = 2;</code>
       * @param value The requestMessage to set.
       * @return This builder for chaining.
       */
      public Builder setRequestMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        requestMessage_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string requestMessage = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestMessage() {
        requestMessage_ = getDefaultInstance().getRequestMessage();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string requestMessage = 2;</code>
       * @param value The bytes for requestMessage to set.
       * @return This builder for chaining.
       */
      public Builder setRequestMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        requestMessage_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.github.quantranuk.protobuf.nio.proto.HeartBeatRequest)
    }

    // @@protoc_insertion_point(class_scope:com.github.quantranuk.protobuf.nio.proto.HeartBeatRequest)
    private static final com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest();
    }

    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeartBeatRequest>
        PARSER = new com.google.protobuf.AbstractParser<HeartBeatRequest>() {
      @java.lang.Override
      public HeartBeatRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<HeartBeatRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeatRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeartBeatResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.quantranuk.protobuf.nio.proto.HeartBeatResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 requestTimeMillis = 1;</code>
     * @return The requestTimeMillis.
     */
    long getRequestTimeMillis();

    /**
     * <code>int64 responseTimeMillis = 2;</code>
     * @return The responseTimeMillis.
     */
    long getResponseTimeMillis();

    /**
     * <code>string responseMessage = 3;</code>
     * @return The responseMessage.
     */
    java.lang.String getResponseMessage();
    /**
     * <code>string responseMessage = 3;</code>
     * @return The bytes for responseMessage.
     */
    com.google.protobuf.ByteString
        getResponseMessageBytes();
  }
  /**
   * Protobuf type {@code com.github.quantranuk.protobuf.nio.proto.HeartBeatResponse}
   */
  public static final class HeartBeatResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.github.quantranuk.protobuf.nio.proto.HeartBeatResponse)
      HeartBeatResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 2,
        /* suffix= */ "",
        HeartBeatResponse.class.getName());
    }
    // Use HeartBeatResponse.newBuilder() to construct.
    private HeartBeatResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private HeartBeatResponse() {
      responseMessage_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.internal_static_com_github_quantranuk_protonio_sample_HeartBeatResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.internal_static_com_github_quantranuk_protonio_sample_HeartBeatResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse.class, com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse.Builder.class);
    }

    public static final int REQUESTTIMEMILLIS_FIELD_NUMBER = 1;
    private long requestTimeMillis_ = 0L;
    /**
     * <code>int64 requestTimeMillis = 1;</code>
     * @return The requestTimeMillis.
     */
    @java.lang.Override
    public long getRequestTimeMillis() {
      return requestTimeMillis_;
    }

    public static final int RESPONSETIMEMILLIS_FIELD_NUMBER = 2;
    private long responseTimeMillis_ = 0L;
    /**
     * <code>int64 responseTimeMillis = 2;</code>
     * @return The responseTimeMillis.
     */
    @java.lang.Override
    public long getResponseTimeMillis() {
      return responseTimeMillis_;
    }

    public static final int RESPONSEMESSAGE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object responseMessage_ = "";
    /**
     * <code>string responseMessage = 3;</code>
     * @return The responseMessage.
     */
    @java.lang.Override
    public java.lang.String getResponseMessage() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string responseMessage = 3;</code>
     * @return The bytes for responseMessage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResponseMessageBytes() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestTimeMillis_ != 0L) {
        output.writeInt64(1, requestTimeMillis_);
      }
      if (responseTimeMillis_ != 0L) {
        output.writeInt64(2, responseTimeMillis_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(responseMessage_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, responseMessage_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestTimeMillis_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, requestTimeMillis_);
      }
      if (responseTimeMillis_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, responseTimeMillis_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(responseMessage_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, responseMessage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse)) {
        return super.equals(obj);
      }
      com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse other = (com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse) obj;

      if (getRequestTimeMillis()
          != other.getRequestTimeMillis()) return false;
      if (getResponseTimeMillis()
          != other.getResponseTimeMillis()) return false;
      if (!getResponseMessage()
          .equals(other.getResponseMessage())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTTIMEMILLIS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestTimeMillis());
      hash = (37 * hash) + RESPONSETIMEMILLIS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getResponseTimeMillis());
      hash = (37 * hash) + RESPONSEMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseMessage().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.quantranuk.protobuf.nio.proto.HeartBeatResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.quantranuk.protobuf.nio.proto.HeartBeatResponse)
        com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.internal_static_com_github_quantranuk_protonio_sample_HeartBeatResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.internal_static_com_github_quantranuk_protonio_sample_HeartBeatResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse.class, com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse.Builder.class);
      }

      // Construct using com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        requestTimeMillis_ = 0L;
        responseTimeMillis_ = 0L;
        responseMessage_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.internal_static_com_github_quantranuk_protonio_sample_HeartBeatResponse_descriptor;
      }

      @java.lang.Override
      public com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse getDefaultInstanceForType() {
        return com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse build() {
        com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse buildPartial() {
        com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse result = new com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.requestTimeMillis_ = requestTimeMillis_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.responseTimeMillis_ = responseTimeMillis_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.responseMessage_ = responseMessage_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse) {
          return mergeFrom((com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse other) {
        if (other == com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse.getDefaultInstance()) return this;
        if (other.getRequestTimeMillis() != 0L) {
          setRequestTimeMillis(other.getRequestTimeMillis());
        }
        if (other.getResponseTimeMillis() != 0L) {
          setResponseTimeMillis(other.getResponseTimeMillis());
        }
        if (!other.getResponseMessage().isEmpty()) {
          responseMessage_ = other.responseMessage_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                requestTimeMillis_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                responseTimeMillis_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                responseMessage_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long requestTimeMillis_ ;
      /**
       * <code>int64 requestTimeMillis = 1;</code>
       * @return The requestTimeMillis.
       */
      @java.lang.Override
      public long getRequestTimeMillis() {
        return requestTimeMillis_;
      }
      /**
       * <code>int64 requestTimeMillis = 1;</code>
       * @param value The requestTimeMillis to set.
       * @return This builder for chaining.
       */
      public Builder setRequestTimeMillis(long value) {

        requestTimeMillis_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 requestTimeMillis = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestTimeMillis() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestTimeMillis_ = 0L;
        onChanged();
        return this;
      }

      private long responseTimeMillis_ ;
      /**
       * <code>int64 responseTimeMillis = 2;</code>
       * @return The responseTimeMillis.
       */
      @java.lang.Override
      public long getResponseTimeMillis() {
        return responseTimeMillis_;
      }
      /**
       * <code>int64 responseTimeMillis = 2;</code>
       * @param value The responseTimeMillis to set.
       * @return This builder for chaining.
       */
      public Builder setResponseTimeMillis(long value) {

        responseTimeMillis_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 responseTimeMillis = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseTimeMillis() {
        bitField0_ = (bitField0_ & ~0x00000002);
        responseTimeMillis_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object responseMessage_ = "";
      /**
       * <code>string responseMessage = 3;</code>
       * @return The responseMessage.
       */
      public java.lang.String getResponseMessage() {
        java.lang.Object ref = responseMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string responseMessage = 3;</code>
       * @return The bytes for responseMessage.
       */
      public com.google.protobuf.ByteString
          getResponseMessageBytes() {
        java.lang.Object ref = responseMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string responseMessage = 3;</code>
       * @param value The responseMessage to set.
       * @return This builder for chaining.
       */
      public Builder setResponseMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        responseMessage_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string responseMessage = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseMessage() {
        responseMessage_ = getDefaultInstance().getResponseMessage();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string responseMessage = 3;</code>
       * @param value The bytes for responseMessage to set.
       * @return This builder for chaining.
       */
      public Builder setResponseMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        responseMessage_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.github.quantranuk.protobuf.nio.proto.HeartBeatResponse)
    }

    // @@protoc_insertion_point(class_scope:com.github.quantranuk.protobuf.nio.proto.HeartBeatResponse)
    private static final com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse();
    }

    public static com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeartBeatResponse>
        PARSER = new com.google.protobuf.AbstractParser<HeartBeatResponse>() {
      @java.lang.Override
      public HeartBeatResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<HeartBeatResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeatResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.quantranuk.protobuf.nio.proto.TestHeartBeat.HeartBeatResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_quantranuk_protonio_sample_HeartBeatRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_github_quantranuk_protonio_sample_HeartBeatRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_quantranuk_protonio_sample_HeartBeatResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_github_quantranuk_protonio_sample_HeartBeatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2protobuf-nio-sample/src/main/proto/Hea" +
      "rtBeat.proto\022%com.github.quantranuk.prot" +
      "onio.sample\"E\n\020HeartBeatRequest\022\031\n\021reque" +
      "stTimeMillis\030\001 \001(\003\022\026\n\016requestMessage\030\002 \001" +
      "(\t\"c\n\021HeartBeatResponse\022\031\n\021requestTimeMi" +
      "llis\030\001 \001(\003\022\032\n\022responseTimeMillis\030\002 \001(\003\022\027" +
      "\n\017responseMessage\030\003 \001(\tB\017B\rTestHeartBeat" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_github_quantranuk_protonio_sample_HeartBeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_quantranuk_protonio_sample_HeartBeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_github_quantranuk_protonio_sample_HeartBeatRequest_descriptor,
        new java.lang.String[] { "RequestTimeMillis", "RequestMessage", });
    internal_static_com_github_quantranuk_protonio_sample_HeartBeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_github_quantranuk_protonio_sample_HeartBeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_github_quantranuk_protonio_sample_HeartBeatResponse_descriptor,
        new java.lang.String[] { "RequestTimeMillis", "ResponseTimeMillis", "ResponseMessage", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
